SpringMVC_ProjectDemo1/src/manaki/web/shop/model/entity/Cart.java
package manaki.web.shop.model.entity;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class Cart {
	
	private List<ProductCart> products;
	
	public Cart() {
		this.products = new ArrayList<ProductCart> ();
	}
	
	public List<ProductCart> getProducts() {
		return this.products;
	}
	
	public int getAmount(String productId) {
		for (ProductCart pc : products) {
			if (pc.getProductId().equals(productId)) return pc.getAmount();
		}
		return 0;
	}
	
	public void addProduct(String productId, int amount) {
		for (ProductCart pc : products) {
			if (pc.getProductId().equals(productId)) {
				pc.setAmount(pc.getAmount() + amount);
				return;
			}
		}
		products.add(new ProductCart(productId));
	}
	
	public void removeProduct(String productId) {
		this.products.removeIf(pc -> pc.getProductId().equals(productId));
	}
	
	public void removeProduct(String productId, int amount) {
		Iterator<ProductCart> i = products.iterator();
		while (i.hasNext()) {
			ProductCart pc = i.next();
			if (pc.getProductId().equals(productId)) {
				int current = pc.getAmount();
				if (current <= amount) {
					i.remove();
					return;
				}
				pc.setAmount(pc.getAmount() - amount);
				return;
			}
		}
	}
	
	public float getSumPrice() {
		float sum = 0;
		for (ProductCart pc : products) {
			sum += pc.getProductSumPrice();
		}
		return sum;
	}
	
}

SpringMVC_ProjectDemo1/src/manaki/web/shop/model/entity/Product.java
package manaki.web.shop.model.entity;

public class Product {
	
	private String productId;
	private String productName;
	private String title;
	private String description;
	//O day de image la String
	private String image;
	private float price;
	
	public Product() {}
	
	public Product(String productId, String productName, String title, String description, String image, float price) {
		super();
		this.productId = productId;
		this.productName = productName;
		this.title = title;
		this.description = description;
		this.image = image;
		this.price = price;
	}

	public String getProductId() {
		return productId;
	}
	
	public void setProductId(String productId) {
		this.productId = productId;
	}
	
	public String getProductName() {
		return productName;
	}
	
	public void setProductName(String productName) {
		this.productName = productName;
	}
	
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getImage() {
		return image;
	}
	
	public void setImage(String image) {
		this.image = image;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}
	
	
	
}

SpringMVC_ProjectDemo1/src/manaki/web/shop/model/entity/ProductCart.java
package manaki.web.shop.model.entity;

import manaki.web.shop.controller.ProductController;

public class ProductCart {
	
	private String productId;
	private int amount; 
	
	public ProductCart(String productId) {
		this.productId = productId;
		this.amount = 1;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}
	
	public String getProductName() {
		Product product = ProductController.getInst().getService().getProductById(this.productId);
		return product.getProductName();
	}
	
	public float getProductSumPrice() {
		Product product = ProductController.getInst().getService().getProductById(this.productId);
		return product.getPrice() * this.amount;
	}
	
}

SpringMVC_ProjectDemo1/src/manaki/web/shop/controller/ProductController.java
package manaki.web.shop.controller;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

import manaki.web.shop.model.entity.Cart;
import manaki.web.shop.model.entity.Product;
import manaki.web.shop.model.service.IProductService;

@Controller
@RequestMapping(value = "/product-controller")
public class ProductController {
	
	// Static
	private static ProductController inst;
	public static ProductController getInst() {
		return inst;
	}
	
	// 
	
	@Autowired
	private IProductService productService;
	
	private Cart cart;
	
	public ProductController() {
		this.cart = new Cart();
		
		inst = this;
	}
	
	public IProductService getService() {
		return this.productService;
	}
	
	@RequestMapping(value = "/cart.htm")
	public ModelAndView showCart() {
		ModelAndView mav = new ModelAndView("cart");
		mav.addObject("cart", cart);
		mav.addObject("service", productService);
		
		return mav;
	}
	
	@RequestMapping(value = "/cart-add.htm")
	public String addToCart(HttpServletRequest request) {
		String productId = request.getParameter("id");
		
		this.cart.addProduct(productId, 1);
		return "redirect:cart.htm";
	}
	
	@RequestMapping(value = "/cart-subtract.htm")
	public String subtractFormCart(HttpServletRequest request) {
		String productId = request.getParameter("id");
		this.cart.removeProduct(productId, 1);
		return "redirect:cart.htm";
	}
	
	@RequestMapping(value = "/cart-remove.htm")
	public String removeFormCart(HttpServletRequest request) {
		String productId = request.getParameter("id");
		this.cart.removeProduct(productId);
		return "redirect:cart.htm";
	}
	
	@RequestMapping(value = "/products.htm")
	public ModelAndView readAll(HttpServletRequest request) {
		ModelAndView mav = new ModelAndView("products");
		List<Product> products = productService.getAllProducts();
		mav.addObject("products", products);
		
		return mav;
	}
	
	@RequestMapping(value = "/create-product.htm")
	public ModelAndView redirectCreate() {
		ModelAndView mav = new ModelAndView("create-product");
		
		mav.addObject("product", new Product());
		
		return mav;
	}
	
	@RequestMapping(value = "/show-product.htm")
	public ModelAndView showProductInfo(HttpServletRequest request) {
		String id = request.getParameter("productId");
		Product product = productService.getProductById(id);
		
		ModelAndView mav = new ModelAndView("product-info");
		
		mav.addObject("product", product);
		
		return mav;
	}
	
	@RequestMapping(value = "/do-create.htm", method = RequestMethod.POST)
	public String doCreate(@ModelAttribute(value = "product") Product product, 
			@RequestParam(name = "productImage") MultipartFile productImage,
			HttpServletRequest request) {
		
		product.setImage(productImage.getOriginalFilename());
		productService.createProduct(product);
		saveImage(request, productImage);
		
		return "redirect:products.htm";
	}
	
	private String saveImage(HttpServletRequest request, MultipartFile multi) {
		try {
			byte[] bytes = multi.getBytes();
			String path = request.getServletContext().getRealPath("/images");
			File file = new File(path);
			File dest = new File(file.getAbsoluteFile() + "/" + multi.getOriginalFilename());
			if (!dest.exists()) {
				Files.write(dest.toPath(), bytes, StandardOpenOption.CREATE);
			}
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return multi.getOriginalFilename();
	}
	
}

SpringMVC_ProjectDemo1/WebContent/WEB-INF/views/cart.jsp
<%@page import="manaki.web.shop.model.entity.Product"%>
<%@page import="manaki.web.shop.controller.ProductController"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="f"%>
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="${pageContext.servletContext.contextPath }/styles/style.css">
    <title>Giỏ đồ</title>
</head>
<body>
    <!-- Menu -->
    <div class="menu">
        <ul class="main-menu">
			<li><a href="products.htm">Mua hàng</a></li>
			<li><a href="cart.htm">Giỏ hàng</a></li>
			<li><a href="create-product.htm">Tạo mới</a></li>
        </ul>
    </div>

    <table class="cart-table">
        <tr style="font-weight: bold;">
            <td>Mã hàng</td>
            <td>Tên hàng</td>
            <td>Số lượng</td>
            <td>Thành tiền</td>
            <td>Hành động</td>
        </tr>
        <% int sum = 0; %>
        
        <!-- Products -->
        <c:forEach items="${cart.products }" var="pc">
	        <tr>
	            <td>${pc.productId }</td>
	            <td>${pc.productName }</td>
	            <td>
	            	<a href="cart-subtract.htm?id=${pc.productId }"><input type="button" value="-"></a>
	                <input type="text" style="width: 25px;" value="${pc.amount}" readonly>
	                <a href="cart-add.htm?id=${pc.productId }"><input type="button" value="+"></a>
	            </td>
	            <td>${pc.productSumPrice }$</td>
	            <td>
	                <a href="cart-remove.htm?id=${pc.productId }">Loại bỏ</a>
	            </td>
	        </tr>
        </c:forEach>
        
        <!-- Sum -->
        <tr>
            <td colspan="5">
                <p>Tổng tiền: ${cart.sumPrice }$</p>
            </td>
        </tr>
    </table>
    
    <a href="products.htm" style="margin-left: 345px; font-size: 20px;">Tiếp tục mua hàng...</a>

</body>
</html>

SpringMVC_ProjectDemo1/WebContent/WEB-INF/views/create-product.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="f"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"
	href="${pageContext.servletContext.contextPath }/styles/style.css">
<script type="text/javascript"
	src="${pageContext.servletContext.contextPath }/libraries/ckeditor/ckeditor.js"></script>
<title>Thêm sản phẩm mới</title>
</head>
<body>
	<!-- Menu -->
	<div class="menu">
		<ul class="main-menu">
			<li><a href="products.htm">Mua hàng</a></li>
			<li><a href="cart.htm">Giỏ hàng</a></li>
			<li><a href="">Tạo mới</a></li>
		</ul>
	</div>

	<f:form action="do-create.htm" modelAttribute="product" method="post" enctype="multipart/form-data">
		<div class="create-container">
			<table id="create">
				<tr>
					<td style="width: 150px;">Nhập ID</td>
					<td style="width: 500px;"><f:input path="productId" /></td>
				</tr>
				<tr>
					<td>Nhập Tên</td>
					<td><f:input path="productName" /></td>
				</tr>
				<tr>
					<td>Nhập Giá</td>
					<td><f:input path="price" /></td>
				</tr>
				<tr>
					<td>Tải ảnh lên</td>
					<td><input type="file" name="productImage"></td>
				</tr>
				<tr>
					<td>Nhập tiêu đề</td>
					<td><f:textarea path="title" style="width: 400px;"/></td>
				</tr>
				<tr>
					<td>Thiết kế Mô tả</td>
					<td><f:textarea path="description" id="description" /></td>
				</tr>
				<tr>
					<td colspan="2"><input type="submit" value="Thêm sản phẩm"
						style="width: 120px; height: 30px"></td>
				</tr>
			</table>
		</div>
	</f:form>

	<script type="text/javascript">
		var desc = CKEDITOR.replace("description");
	</script>

</body>
</html>

SpringMVC_ProjectDemo1/WebContent/WEB-INF/views/product-info.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="f"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="${pageContext.servletContext.contextPath }/styles/style.css">
    <title>Thông tin sản phẩm</title>
</head>
<body>
    <!-- Menu -->
    <div class="menu">
        <ul class="main-menu">
			<li><a href="products.htm">Mua hàng</a></li>
			<li><a href="">Giỏ hàng</a></li>
			<li><a href="create-product.htm">Tạo mới</a></li>
        </ul>
    </div>
    
    <!-- Product  -->
    <div class="product-info">
        <div class="title">${product.title }</div>
        <div class="name">${product.productName }</div>
        <div class="image" style="margin-top: 20px; margin-bottom: 20px;">
            <img src="${pageContext.request.contextPath }/images/${product.image }" alt="">
        </div>
        <div class="desc">
            ${product.description } 
        </div>
    </div>
</body>
</html>

SpringMVC_ProjectDemo1/WebContent/WEB-INF/views/products.jsp
<%@page import="manaki.web.shop.utils.Utils"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="f"%>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="${pageContext.servletContext.contextPath }/styles/style.css">
<title>Mua hàng</title>
</head>
<body>
	<!-- Menu -->
	<div class="menu">
		<ul class="main-menu">
			<li><a href="">Mua hàng</a></li>
			<li><a href="cart.htm">Giỏ hàng</a></li>
			<li><a href="create-product.htm">Tạo mới</a></li>
		</ul>
	</div>

	<c:forEach items="${products }" var="product">
		<!-- Product  -->
		<div class="product" onclick="location.href='show-product.htm?productId=${product.productId}';">
			<div class="image">
				<img src="${pageContext.request.contextPath }/images/${product.image }" alt="">
			</div>
			<div class="desc">
				<div class="title">${product.title }</div>
				<div class="name" style="display: flex; height: 20px;">
					<p style="margin-right: 5px;">Mặt hàng:</p>
					<p>${product.productName }</p>
				</div>
				<div class="price">
					<p style="font-weight: bold;">${product.price }$</p>
				</div>
				<div class="short-desc" style="margin-bottom: 10px;">
					${product.description }</div>
				<div class="buy-now">
					<a href="cart-add.htm?id=${product.productId }">Đừng mua, vẫn mua thì bấm vào</a>
				</div>
			</div>
		</div>
	</c:forEach>


</body>
</html>